# Stage 1: Compile and Build angular 
FROM node:erbium-alpine as build
RUN apk --no-cache add tzdata=2022a-r0
ENV TZ=America/Buenos_Aires
WORKDIR /usr/local/app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

# Stage 2: Serve app with nginx server

FROM nginx:latest
COPY --from=build /usr/local/app/dist/ /usr/share/nginx/html
EXPOSE 80
HEALTHCHECK NONE

